apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-credentials
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "10"  
spec:
  encryptedData:
    credentials: AgB1PjFZtamhklm3ADxBq6K1fJLij4OIIMLA0iyrJO/EvcVe0jpdS1qPm/RVYYVKV1v0C3FygR6NxTwiGmzf31a/1KZ27/WYvHPYoZxn4WMGDZjc8dTc/kUrx2UT/AuwxMp82/+gh14iDXvORio0QOG09L8Ae6JaiS4D5/cSvE4nETSKj8Bx1WeVcNiUoT6YGlLQI4Xr+SXOziqC6ETPs2Co2drcgXQQWAgzihqZuexblgb4Ru3uLSJLXUHfucK+bEim2M4W4qPiVgAENBUYhF6Y+ki/ehw/S31cfmMD9CJw4GRUU8CZAu/EPooBvOH8OFs7KNrcxfPnOeHTgyf3Ta/P2W4+p3am8Ff/21xKD6bkPYSsicN0qaS94+rSYtZt3+hvpN/MbJdnZ5BVL9nf0awQW94X1uv7SgmEs47wdihXQH7CnEabpPjz5orC0XKniE5ARLvVMb59xRahW5hHZcZwpIO/NTj3HJWLXe0jAL23D72RTRSSv19cAr7nXCC8gzI//zAqEnLIPrGd53Ao6n9gyD554LdZlmt2UNYQ5XQJkCv/kC1CDtkqftGPkyLG+efpLiDSDXJXCohPfk7PFhAtCfnBx6clVLVbnm1/CJhiVRbhJzrbTqrAQyErZ79Q8DN+HmfiHDVAMhjaJ+zJSXRc7nHhOA++LsOLeStd7P2Amt8gcDsPA8KyhwX5GIvikZ0eUzWIqQsumjC/Gz+J2Z5btXM9fGwLCL+KXCN40B++XMEJ/DcTFk11ONcy51YShfH2kUkPdsmz0YVdnf2NUs2UB+aFMWkP+DUzEM0ZqySqyNVj5jw15G8O9F6iA01VyvF2rl7mmfjiM38ACWqNK3EyZURhjw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-credentials
      namespace: crossplane-system

