#
# This Secret is applied to the management cluster where Argo CD is installed.
# It contains the API token and certificate authority data associated with a service account in the remote cluster
# This enables Argo CD to perform operations against the remote cluster, using the credentials of the service account
#
# Here is what the "data" section of the Secret contains:
# name: Base64 encoded friendly name of the cluster. Note this does not have to be the exact same name of the remote cluster
# server: Base64 encoded endpoint of the remote cluster.
# config: Base64 encoded string of the following JSON data which has the API token and CA certificate of the service account in the remote cluster
#
# {
#    "bearerToken": Unencoded API token of the service account retrieved from the Secret created in the remote cluster
#    "tlsClientConfig":{
#       "insecure":false,
#       "caData": Encoded CA certificate for the service account retrieved from the Secret created in the remote cluster
#    }
# }
#
---
apiVersion: v1
kind: Secret
metadata:
  name: crossplane-argocd-cluster-j4mzk
  namespace: argocd
  annotations:
    managed-by: argocd.argoproj.io  
  labels:
    argocd.argoproj.io/secret-type: cluster  
data:
  name: 
  server: 
  config: 

